version: '3.1'

services:
  wic-remix-migrate:
    build:
      target: test
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:incredible_local_secret_phrase@database-e2e:5432/postgres?schema=public
    depends_on:
      database-e2e:
        condition: service_healthy
    command: >
      bash -c "npx prisma migrate dev && npx prisma db seed"
  database-e2e:
    image: postgres
    environment:
      POSTGRES_PASSWORD: incredible_local_secret_phrase
      POSTGRES_USER: postgres
    healthcheck:
      test: "pg_isready --username=postgres"
      timeout: 5s
      retries: 20
    ports:
      - 5554:5432
